export const experiences = [
	{
		title: "Graduate Assistant",
		company: "Clemson University",
		location: "Clemson, SC (Remote)",
		period: "Nov 2024 — May 2026",
		current: true,
		highlights: [
			"Built Prepitus, an AI-powered Digital SAT tutoring platform with a graduate research team — contributing across frontend, backend, infrastructure, and payments.",
			"Developed the React.js frontend and Node.js/Express.js backend on DynamoDB and AWS (EC2, S3), delivering the end-to-end web application from design through production.",
			"Sole developer of the end-to-end Stripe payment integration, including checkout flows and subscription management.",
			"Delivered 10 full-length SAT mock tests, a 787-question topic-scoped practice bank, and OpenAI-generated concept quizzes for unlimited on-demand practice.",
			"Built and deployed a Deep Knowledge Tracing (DKT) service — an LSTM model scoring per-student mastery across 30 SAT knowledge components — as a FastAPI inference API on AWS, personalizing recommendations for 450+ students.",
		],
		tech: [
			"React.js",
			"Node.js",
			"Express.js",
			"DynamoDB",
			"AWS",
			"Stripe",
			"OpenAI",
			"FastAPI",
			"Python",
		],
	},
	{
		title: "Full Stack Developer",
		company: "Wipro Ltd",
		location: "Mumbai, India",
		period: "Apr 2022 — May 2024",
		current: false,
		highlights: [
			"Built the Leap onboarding portal — a MERN-stack platform unifying customer and policy onboarding for Aditya Birla Sun Life Insurance (ABSLI) across seven retail business streams.",
			"Developed full-stack features integrating 30+ third-party services including credit checks (CRIF), identity verification (HyperVerge), and core insurance platforms.",
			"Implemented redundant-provider fallback logic to keep onboarding flows live during third-party outages.",
			"Replaced ABSLI's legacy onboarding system; delivered 12+ insurance products with performance optimizations reducing average execution time by 35–40%.",
		],
		tech: ["React.js", "Node.js", "Express.js", "MongoDB", "REST APIs"],
	},
];

export const education = [
	{
		degree: "Master of Science, Computer Science",
		school: "Clemson University",
		location: "Clemson, SC",
		period: "Aug 2024 — Present",
		gpa: "3.86 / 4.0",
	},
	{
		degree: "Bachelor of Engineering, Computer Engineering",
		school: "St. Francis Institute of Technology",
		location: "Mumbai, India",
		period: "Aug 2018 — May 2022",
		gpa: "8.14 / 10",
	},
];

export const projects = [
	{
		name: "Prepitus",
		tagline: "AI-Powered SAT Tutoring Platform",
		description:
			"Graduate research platform with 10 full-length SAT mock tests, a 787-question practice bank, OpenAI-generated concept quizzes, and a Deep Knowledge Tracing LSTM model that personalizes recommendations for 450+ students across 30 knowledge components.",
		tech: [
			"React.js",
			"Node.js",
			"DynamoDB",
			"AWS EC2/S3",
			"Stripe",
			"OpenAI",
			"FastAPI",
			"Python",
		],
		liveUrl: null,
		githubUrl: null,
		label: "Research",
		featured: true,
	},
	{
		name: "KotiKutz",
		tagline: "Full-Stack Barbershop Booking Platform",
		description:
			"Full-stack booking platform with role-based access (customer, employee, manager, super admin), multi-step appointment flow, SSR for SEO, transactional email notifications via Nodemailer, admin dashboard with analytics, and Stripe payments.",
		tech: [
			"Next.js 16",
			"React 19",
			"TypeScript",
			"Supabase",
			"Tailwind CSS",
			"Stripe",
			"Nodemailer",
		],
		liveUrl: "https://koti-kutz.vercel.app",
		githubUrl: "https://github.com/gaurav2055/KotiKutz",
		label: "Freelance",
		featured: true,
	},
	{
		name: "7Square",
		tagline: "Real Estate Listings Platform",
		description:
			"Real estate platform featuring property listings, company profile, user authentication, and an admin section for managing listings. Customers can browse properties and contact the agency directly through the site.",
		tech: ["React.js", "Node.js", "Express.js", "Firebase"],
		liveUrl: "https://www.7squarerealtors.in/",
		githubUrl: "https://github.com/gaurav2055/seven_square_frontend",
		label: "Freelance",
		featured: false,
	},
	{
		name: "Dream Travel Recommender",
		tagline: "AI-Assisted Travel Recommendation App",
		description:
			"AI-powered travel recommendation app with a React frontend and a Python/Node.js backend that provides personalized travel suggestions based on user preferences.",
		tech: ["React", "Node.js", "Express", "Python", "FastAPI"],
		liveUrl: null,
		githubUrl: "https://github.com/gaurav2055/Dream-Travel-Recommender-frontend",
		label: "Personal",
		featured: false,
	},
	{
		name: "Job Tracker",
		tagline: "Job Application Tracking Tool",
		description:
			"A clean tool for tracking job applications, statuses, and follow-ups — built to solve a real need during the job search process.",
		tech: ["JavaScript", "React", "Vercel"],
		liveUrl: "https://job-tracker-lac-alpha.vercel.app",
		githubUrl: "https://github.com/gaurav2055/job-tracker",
		label: "Personal",
		featured: false,
	},
	{
		name: "D-Monitor",
		tagline: "Disaster Monitoring & Response System",
		description:
			"Cross-platform Flutter mobile app for on-the-go disaster monitoring — integrating live telemetry maps, real-time analytics, news feeds, and tweet streams. Built a data pipeline using Scrapy for live alert scraping and applied SVM, BERT, and sentiment analysis in Python, with results indexed in Elasticsearch on GCP. Developed as part of a 4-person team for final year capstone.",
		tech: [
			"Flutter",
			"Dart",
			"Python",
			"Scrapy",
			"BERT",
			"SVM",
			"Elasticsearch",
			"GCP",
			"Node.js",
		],
		liveUrl: null,
		githubUrl: null,
		label: "Academic",
		featured: false,
	},
];

export const skills: Record<string, string[]> = {
	Frontend: [
		"React.js",
		"Next.js",
		"TypeScript",
		"JavaScript",
		"Tailwind CSS",
		"Redux Toolkit",
		"Material UI",
		"Bootstrap",
		"HTML",
		"CSS",
	],
	Backend: [
		"Node.js",
		"Express.js",
		"Python",
		"FastAPI",
		"GraphQL",
		"REST APIs",
		"JWT",
		"NextAuth",
		"Stripe",
		"Nodemailer",
	],
	Databases: ["MongoDB", "DynamoDB", "PostgreSQL", "MySQL", "Firebase", "Prisma", "Mongoose"],
	"Cloud & DevOps": [
		"AWS",
		"GCP",
		"Supabase",
		"Vercel",
		"Docker",
		"Kubernetes",
		"GitHub Actions",
		"Jenkins",
		"Nginx",
	],
	Mobile: ["Flutter", "Dart"],
	Tools: ["Git", "GitHub", "Jest", "Figma", "Postman", "AWS CLI"],
};
